WebUI/3DLContentManagement/Controllers/ApkController.cs
using _3DLContentManagement.Common;
using _3DLContentManagement.Database;
using _3DLContentManagement.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using TDL.ContentPlatform.Server.Database.Tables;

namespace _3DLContentManagement.Controllers
{
    public class ApkController : Controller
    {
        // GET: Apk
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllApks([DataSourceRequest] DataSourceRequest request)
        {
            List<ApkDetail> listApks = new List<ApkDetail>();
            using (DB_Entities db = new DB_Entities())
            {
                var apks = db.ApkDetail.Where(x => x.IsDeleted == false).OrderBy(x => x.ApkVersion).ToList();

                listApks = apks.Select(apk => new ApkDetail()
                {
                    ApkId = apk.ApkId,
                    ApkName = apk.ApkName,
                    ApkVersion = apk.ApkVersion,
                    ApkDescription = apk.ApkDescription,
                    PublishApk = apk.PublishApk,
                    IsMandatory = apk.IsMandatory,
                    IsActive = Convert.ToBoolean(apk.IsActive != null ? apk.IsActive : true),
                    IsDeleted = Convert.ToBoolean(apk.IsDeleted != null ? apk.IsDeleted : false),
                    CreatedBy = apk.CreatedBy != null ? apk.CreatedBy.Value : new Guid(),
                    CreatedOn = apk.CreatedOn != null ? apk.CreatedOn.Value : DateTime.UtcNow
                }).ToList();
            }

            var jsonResult = Json(listApks.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public bool ActiveApk(int Id)
        {
            using (DB_Entities db = new DB_Entities())
            {
                var apk = db.ApkDetail.Where(x => x.ApkId == Id).FirstOrDefault();
                if (apk != null)
                {
                    apk.IsActive = true;
                    db.SaveChanges();
                }
            }

            return true;
        }

        public bool InactiveApk(int Id)
        {
            using (DB_Entities db = new DB_Entities())
            {
                var apk = db.ApkDetail.Where(x => x.ApkId == Id).FirstOrDefault();
                if (apk != null)
                {
                    apk.IsActive = false;
                    db.SaveChanges();
                }
            }

            return true;
        }

        public bool DeleteApk(int Id)
        {
            using (DB_Entities db = new DB_Entities())
            {
                var apk = db.ApkDetail.Where(x => x.ApkId == Id).FirstOrDefault();
                if (apk != null)
                {
                    apk.IsDeleted = true;
                    db.SaveChanges();
                }
            }

            return true;
        }

        public ActionResult AddUpdateApk(int Id)
        {
            ApkDetail apk = new ApkDetail();
            using (DB_Entities db = new DB_Entities())
            {
                if (Id == 0)
                {
                    apk.ApkId = Id;
                    apk.IsMandatory = false;
                    apk.IsActive = true;
                    apk.IsDeleted = false;
                    ViewBag.AddedType = "Add";
                }
                else
                {
                    var record = db.ApkDetail.Where(x => x.ApkId == Id).FirstOrDefault();
                    if (record != null)
                    {
                        apk.ApkId = record.ApkId;
                        apk.ApkName = record.ApkName;
                        apk.ApkDescription = record.ApkDescription;
                        apk.ApkVersion = record.ApkVersion;
                        apk.PublishApk = record.PublishApk;
                        apk.IsMandatory = record.IsMandatory;
                        apk.IsActive = record.IsActive ?? true;
                        apk.IsDeleted = record.IsDeleted ?? false;                       
                    }

                    ViewBag.AddedType = "Edit";
                }
            }

            return View(apk);
        }

        [HttpPost]
        public async Task<ActionResult> AddUpdateApk(ApkDetail apk)
        {
            if (apk.ApkId != 0 || apk.ApkName != null)
            {
                try
                {
                    //HttpPostedFileBase UploadFile (UploadFile != null && UploadFile.ContentLength > 0)
                    //if (UploadFile != null && UploadFile.ContentLength > 0)
                    //{
                    //    string path = string.Empty;
                    //    path = System.IO.Path.Combine(WebConfigurationManager.AppSettings["PublishPath"].ToString(), "apks");

                    //    // get path including filename
                    //    path = Path.Combine(path, UploadFile.FileName);
                    //    //UploadFile.SaveAs(path);
                    //    apk.ApkName = string.IsNullOrWhiteSpace(apk.ApkName) ? UploadFile.FileName : apk.ApkName.Trim();
                    //    apk.PublishApk = path;
                    //}
                    string sourcePath = System.IO.Path.Combine(WebConfigurationManager.AppSettings["SourcePath"].ToString(), "apk");
                    string targetPath = System.IO.Path.Combine(WebConfigurationManager.AppSettings["PublishPath"].ToString(), "apks");

                    //Get the files having same name
                    string[] files = Directory.GetFiles(sourcePath, apk.ApkName);

                    if (files.Length > 0)
                    {
                        foreach (string filename in files)
                        {
                            string file = Path.Combine(targetPath, apk.ApkName);
                            using (FileStream SourceStream = System.IO.File.Open(filename, FileMode.Open, FileAccess.Read))
                            {
                                using (FileStream DestinationStream = System.IO.File.Open(file, FileMode.OpenOrCreate, FileAccess.ReadWrite))
                                {
                                    await SourceStream.CopyToAsync(DestinationStream);
                                }
                            }

                            apk.PublishApk = file;
                        }

                        using (DB_Entities db = new DB_Entities())
                        {
                            if (apk.ApkId == 0)
                            {
                                ApkDetail newApkObj = new ApkDetail()
                                {
                                    //Id = Provider.Sql.Create(),
                                    ApkName = apk.ApkName,
                                    ApkVersion = apk.ApkVersion,
                                    IsMandatory = apk.IsMandatory,
                                    PublishApk = apk.PublishApk,
                                    IsActive = apk.IsActive,
                                    CreatedBy = new Guid(Session["UserID"].ToString()),
                                    CreatedOn = DateTime.UtcNow,
                                    IsDeleted = false
                                };
                                db.ApkDetail.Add(newApkObj);
                                db.SaveChanges();

                                apk.ApkId = newApkObj.ApkId;
                                TempData["Message"] = "Apk added successfully!";
                            }
                            else
                            {
                                var apkObj = db.ApkDetail.Where(x => x.ApkId == apk.ApkId && x.IsDeleted == false).FirstOrDefault();
                                if (apkObj != null)
                                {
                                    apkObj.ApkName = apk.ApkName;
                                    apkObj.ApkVersion = apk.ApkId;
                                    apkObj.ApkDescription = apk.ApkDescription;
                                    apkObj.IsMandatory = apk.IsMandatory;
                                    apkObj.IsActive = apk.IsActive;
                                    apkObj.ModifiedBy = new Guid(Session["UserID"].ToString());
                                    apkObj.ModifiedOn = DateTime.UtcNow;
                                    apkObj.IsDeleted = apk.IsDeleted;
                                    db.Entry(apkObj).State = EntityState.Modified;
                                    db.SaveChanges();
                                }

                                TempData["Message"] = "Apk details updated successfully!";
                            }
                        }
                    }
                    else
                    {
                        TempData["Message"] = "Apk file is not available at FTP.";
                    }
                }
                catch (Exception)
                {
                    TempData["Message"] = "Exception occured.";
                }
            }
            else
            {
                TempData["Message"] = "Enter valid apk filename.";
            }            

            return View(apk);
        }
    }
}

WebUI/3DLContentManagement/Controllers/AppMasterController.cs
using _3DLContentManagement.App_Start;
using _3DLContentManagement.Common;
using _3DLContentManagement.Database;
using _3DLContentManagement.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.EntityFrameworkCore;
using RT.Comb;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TDL.ContentPlatform.Server.Database.Tables;

namespace _3DLContentManagement.Controllers
{
    [Authorize]
    [SessionExpire]
    public class AppMasterController : Controller
    {
        // GET: AppMaster
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllApps([DataSourceRequest] DataSourceRequest request)
        {
            List<AppViewModel> listUsers = DataAccess.GetAppList();
            var jsonResult = Json(listUsers.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public bool ActiveApp(Guid Id)
        {
            using(DB_Entities db = new DB_Entities())
            {
                var record = db.AppMaster.Where(x => x.Id == Id).FirstOrDefault();
                if(record != null)
                {
                    record.IsActive = true;
                    db.SaveChanges();
                }
            }

            return true;
        }

        public bool InactiveApp(Guid Id)
        {
            using (DB_Entities db = new DB_Entities())
            {
                var record = db.AppMaster.Where(x => x.Id == Id).FirstOrDefault();
                if (record != null)
                {
                    record.IsActive = false;
                    db.SaveChanges();
                }
            }

            return true;
        }

        public bool DeleteApp(Guid Id)
        {
            using (DB_Entities db = new DB_Entities())
            {
                var record = db.AppMaster.Where(x => x.Id == Id).FirstOrDefault();
                if (record != null)
                {
                    record.IsDeleted = true;
                    db.SaveChanges();
                }
            }

            return true;
        }

        public ActionResult AddUpdateApp(Guid Id)
        {
            AppViewModel app = new AppViewModel();
            using (DB_Entities db = new DB_Entities())
            {
                var users = DataAccess.GetUsers();
                ViewBag.Users = users.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();

                if (Id == Guid.Empty)
                {
                    app.ID = Guid.Empty;
                    app.IsActive = true;
                    app.IsDeleted = false;
                    ViewBag.AddedType = "Add";
                }
                else
                {
                    var record = db.AppMaster.Where(x => x.Id == Id).FirstOrDefault();
                    if(record != null)
                    {
                        app.ID = record.Id;
                        app.AppName = record.AppName;
                        app.AppID = record.AppId;
                        app.UserID = record.UserId;
                        app.User = users.Where(x => x.Id == record.UserId).FirstOrDefault().Name;
                        app.IsActive = record.IsActive ?? true;
                        app.IsDeleted = record.IsDeleted ?? false;
                    }
                    ViewBag.AddedType = "Edit";
                }
            }

            return View(app);
        }

        [HttpPost]
        public ActionResult AddUpdateApp(AppViewModel app)
        {
            using (DB_Entities db = new DB_Entities())
            {
                if (app.ID == Guid.Empty)
                {
                    AppMaster newAppObj = new AppMaster()
                    {
                        //Id = Provider.Sql.Create(),
                        AppId = app.AppID.Trim(),
                        AppName = app.AppName,
                        UserId = app.UserID,
                        IsActive = app.IsActive,
                        CreatedBy = new Guid(Session["UserID"].ToString()),
                        CreatedOn = DateTime.Now,
                        IsDeleted = false
                    };
                    db.AppMaster.Add(newAppObj);
                    db.SaveChanges();

                    app.ID = newAppObj.Id;
                    TempData["Message"] = "App added successfully!";
                }
                else
                {
                    var appObj = db.AppMaster.Where(x => x.Id == app.ID && x.IsDeleted == false).FirstOrDefault();
                    if (appObj != null)
                    {
                        appObj.AppId = app.AppID;
                        appObj.AppName = app.AppName;
                        appObj.UserId = app.UserID;
                        appObj.IsActive = app.IsActive;
                        appObj.ModifiedBy = new Guid(Session["UserID"].ToString());
                        appObj.ModifiedOn = DateTime.Now;
                        appObj.IsDeleted = app.IsDeleted;
                        db.Entry(appObj).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                    TempData["Message"] = "App details updated successfully!";
                }

                var users = DataAccess.GetUsers();
                ViewBag.Users = users.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
            }

            return View(app);
        }
    }
}

WebUI/3DLContentManagement/Controllers/AssetController.cs
using _3DLContentManagement.App_Start;
using _3DLContentManagement.Common;
using _3DLContentManagement.Database;
using _3DLContentManagement.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _3DLContentManagement.Controllers
{
    [RoleAuthorize]
    [SessionExpire]
    public class AssetController : Controller
    {
        // GET: Asset
        public ActionResult Asset()
        {
            return View();
        }

        public ActionResult Package()
        {
            return View();
        }

        public ActionResult GetAllAssets([DataSourceRequest] DataSourceRequest request)
        {
            List<AssetViewModel> listAssets = DataAccess.GetAssetDetails();
            var jsonResult = Json(listAssets.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
            //return Json(listAssets.ToDataSourceResult(request));
        }

        public ActionResult AssetPublishStatus()
        {
            return View();
        }

        public ActionResult GetAssetPublishStatus([DataSourceRequest] DataSourceRequest request)
        {
            List<AssetPublishStatusModel> listAssetPlatforms = DataAccess.GetAssetPublishStatusByPlatform();
            var jsonResult = Json(listAssetPlatforms.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;            
        }

        public ActionResult GetAllPackages([DataSourceRequest] DataSourceRequest request)
        {
            List<AssetViewModel> listPackages = DataAccess.GetPackageDetails();
            var jsonResult = Json(listPackages.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        #region Download Excel
        [HttpPost]
        public ActionResult Excel_Export_Asset(string contentType, string base64, string fileName)
        {
            var fileContents = Convert.FromBase64String(base64);

            return File(fileContents, contentType, fileName);
        }
        #endregion

        public ActionResult About()
        {
            return View();
        }
    }
}

WebUI/3DLContentManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 3DL Content Management</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
    <link href="~/Content/bootstrap-multiselect.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/kendo/css/kendo.common.css" rel="stylesheet" />
    <link href="~/Content/kendo/css/kendo.default.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <script src="~/Scripts/jquery.mask.min.js"></script>
    <script src="~/Scripts/jquery.mCustomScrollbar.js"></script>
    <script src="~/Content/kendo/js/kendo.all.min.js"></script>
    <script src="~/Content/kendo/js/kendo.aspnetmvc.min.js"></script>
    <script src="~/Content/kendo/js/jszip.min.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/loadingoverlay.js"></script>
    <script src="~/Scripts/loadingoverlay_progress.js"></script>
    <script src="~/Scripts/layout.js?v=6"></script>
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:200,300,300i,400,400i,500,600,700|Oswald:300,400,500,600">
    <style>
        .dropbtn:hover, .dropbtn:focus {
            background-color: #2980B9;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        /* Dropdown button */
        .dropdown .dropbtn {
            border: none;
            outline: none;
            color: white;
            padding: 14px 16px;
            background-color: inherit;
            font-family: inherit; /* Important for vertical align on mobile phones */
            margin: 0; /* Important for vertical align on mobile phones */
        }

        /* Dropdown content (hidden by default) */
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        /* Links inside the dropdown */
        .dropdown-content a {
            float: none;
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: left;
        }

        /* Add a grey background color to dropdown links on hover */
        .dropdown-content a:hover {
            background-color: #ddd;
        }

        .show {
            display: block;
        }

        /* Show the dropdown menu on hover */
        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top my-nav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/images/3dl.png" style="width: 25px; float: left; margin: 8px 10px 0 0;" />
                @if (HttpContext.Current.Request.IsAuthenticated)
                {
                    @Html.ActionLink("Content Management", "Index", "Content", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Content Management", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                @if (HttpContext.Current.Request.IsAuthenticated)
                {
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Home", "Index", "Content")</li>
                    <li>@Html.ActionLink("Asset List", "Assets", "Home")</li>
                    <li>@Html.ActionLink("Activities", "Index", "Activities")</li>
                    <li>@Html.ActionLink("Compounds", "Index", "Compound")</li>
                    <li>@Html.ActionLink("User Management", "Index", "UserManagement")</li>
                    <li>
                        <div class="dropdown">
                            <button class="dropbtn" onclick="myFunction()">
                                Useful links
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div id="myDropdown" class="dropdown-content">
                                @Html.ActionLink("App Master", "Index", "AppMaster")
                                @Html.ActionLink("Apk Details", "Index", "Apk")
                                @Html.ActionLink("Feedback", "Index", "ManageFeedback")
                                @Html.ActionLink("Master Data", "MasterData", "Home")
                                @Html.ActionLink("Export Asset List", "Asset", "Asset")
                                @Html.ActionLink("Asset Publish Status", "AssetPublishStatus", "Asset")
                                @Html.ActionLink("Export Package Details", "Package", "Asset")
                                @Html.ActionLink("About 3DL Content", "About", "Asset")
                            </div>
                        </div>
                    </li>
                </ul>                    
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/Account/ChangePassword">Welcome @Session["Name"]</a></li>
                        <li><a onclick="ClearData();" href="/Account/Logout">Logout</a></li>
                        @*<li>@Html.ActionLink("Logout", "Logout", "Account")</li>*@
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer id="footer">
        <div class="col-md-12">
            <p style="text-align:center;">  &copy; @DateTime.Now.Year - 3DL, Inc. All Rights Reserved.</p>
        </div>
    </footer>

    <div id="messageModel" class="modal fade">
        <div class="vertical-alignment-helper">
            <div class="modal-dialog vertical-align-center">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Message</h4>
                    </div>

                    <div id="msg-p" class="modal-body">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="ContentModal" role="dialog">
        <div class="modal-dialog modal-lg">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="btnClose" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">View File</h4>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div id="divContent"></div>
                        </div>
                        <!-- /.row -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $(".k-grid-add").attr("data-toggle", "tooltip", "data-placement", "top");
            $("a.k-grid-add").prepend('<i class="fa fa-plus fa-1x text-white" aria-hidden="true"></i> ');
        });

        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }
        
        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {

                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
</body>
</html>