WebUI/3DLContentManagement/Controllers/ManagePropertyController.cs
using _3DLContentManagement.App_Start;
using _3DLContentManagement.Common;
using _3DLContentManagement.Database;
using _3DLContentManagement.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TDL.ContentPlatform.Server.Database.Tables;

namespace _3DLContentManagement.Controllers
{
    [RoleAuthorize]
    public class ManagePropertyController : Controller
    {
        // GET: ManageProperty
        public ActionResult Index()
        {
            return View();
        }

        #region Select
        public ActionResult GetAll([DataSourceRequest] DataSourceRequest request)
        {
            List<MstProperty> listProperties = new List<MstProperty>();
            using (DB_Entities db = new DB_Entities())
            {
                var propertys = db.MstProperty.Where(x => x.IsDeleted == false).OrderBy(x => x.PropertyName).ToList();

                listProperties = propertys.Select(property => new MstProperty()
                {
                    PropertyId = property.PropertyId,
                    PropertyName = property.PropertyName,
                    IsActive = Convert.ToBoolean(property.IsActive != null ? property.IsActive : true),
                    IsDeleted = Convert.ToBoolean(property.IsDeleted != null ? property.IsDeleted : false),
                    CreatedBy = property.CreatedBy != null ? property.CreatedBy.Value : new Guid(),
                    CreatedOn = property.CreatedOn != null ? property.CreatedOn.Value : DateTime.UtcNow
                }).ToList();

            }

            return Json(listProperties.ToDataSourceResult(request));
        }

        [HttpGet]
        public JsonResult GetProperties(string q, string selRec)
        {
            q = q.Replace("'", "''");
            List<int> exclude = new List<int>();
            if (!string.IsNullOrWhiteSpace(selRec) && selRec != "null")
            {
                if (selRec.IndexOf(",") > 0)
                {
                    foreach (string s in selRec.Split(','))
                    {
                        exclude.Add(Convert.ToInt32(s));
                    }
                }
                else
                {
                    exclude.Add(Convert.ToInt32(selRec));
                }
            }


            using (DB_Entities db = new DB_Entities())
            {
                var propertys = (from T in db.MstProperty
                            where T.IsDeleted == false && !exclude.Contains(T.PropertyId) && (q == "" || T.PropertyName.Contains(q))
                            select new PropertyNamesModel
                            {
                                PropertyId = T.PropertyId,
                                Name = T.PropertyName
                            }).OrderBy(X => X.Name).ToList();
                return Json(new
                {
                    results = propertys.Select(x => new
                    {
                        id = x.PropertyId,
                        text = x.Name
                    }),
                    more = false
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult AddUpdateProperty(int propertyId)
        {
            PropertyViewModel propertyViewModel = new PropertyViewModel
            {
                PropertyId = propertyId,
                IsActive = true,
                IsDeleted = false
            };
            if (propertyId == 0)
            {
                PropertyNamesModel newPropertyName = new PropertyNamesModel() { PropertyId = 0, Name = string.Empty };
                propertyViewModel.PropertyNames = new List<PropertyNamesModel>();
                propertyViewModel.PropertyNames.Add(newPropertyName);

                using (DB_Entities db = new DB_Entities())
                {
                    ViewBag.Language = db.CsNewLanguage.Select(x => new SelectListItem { Text = x.NewName, Value = x.NewLanguageid.ToString() }).OrderBy(x => x.Text).ToList();
                }
            }
            else
            {
                using (DB_Entities db = new DB_Entities())
                {
                    var property = db.MstProperty.Where(a => a.PropertyId == propertyId).FirstOrDefault();
                    propertyViewModel.IsActive = property.IsActive;

                    propertyViewModel.PropertyNames = (from T in db.MstPropertyNames
                                             join L in db.CsNewLanguage on T.LanguageId equals L.NewLanguageid into TL
                                             from D in TL.DefaultIfEmpty()
                                             where T.PropertyId == propertyId && T.IsDeleted == false
                                             select new PropertyNamesModel
                                             {
                                                 PropertyId = T.PropertyId,
                                                 IsDeleted = T.IsDeleted,
                                                 LanguageId = T.LanguageId,
                                                 Language = D.NewName,
                                                 Id = T.Id,
                                                 Name = T.Name
                                             }).ToList();

                    ViewBag.Language = db.CsNewLanguage.Select(x => new SelectListItem { Text = x.NewName, Value = x.NewLanguageid.ToString() }).OrderBy(x => x.Text).ToList();
                }
            }

            return PartialView("_AddUpdateProperty", propertyViewModel);
        }

        #endregion

        #region Add       
        [HttpPost]
        public async Task<JsonResult> AddUpdateProperty(MstProperty property)
        {
            if (property.PropertyNames != null && property.PropertyNames.Count > 0)
            {
                if (CheckProperties(property.PropertyNames.ElementAt(0).Name, property.PropertyId))
                {
                    return this.Json(new DataSourceResult
                    {
                        Errors = "ALREADY_EXISTS"
                    });
                }

                MstProperty at = new MstProperty();
                if (property != null)
                {
                    at = await AddUpdatePropertyDB(property);
                }

                if (at.PropertyId == 0)
                {
                    return Json(new
                    {
                        isSuccess = false,
                        message = "Error adding property"
                    });
                }
                else
                {
                    return Json(new
                    {
                        isSuccess = true,
                        message = property.PropertyId == 0 ? "Property added successfully." : "Property updated successfully."
                    });
                }
            }
            else
            {
                return Json(new
                {
                    isSuccess = false,
                    message = "Please add atleast one property"
                });
            }
        }
        #endregion

        [HttpGet]
        public JsonResult CheckProperty(string PropertyName, int Id)
        {
            return Json(CheckProperties(PropertyName, Id), JsonRequestBehavior.AllowGet);

        }

        #region Delete
        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> DeleteProperty([DataSourceRequest] DataSourceRequest request, MstProperty property)
        {
            MstProperty at = new MstProperty();
            if (property != null)
            {
                property.IsDeleted = true;
                at = await AddUpdatePropertyDB(property);
            }

            return Json(new[] { at }.ToDataSourceResult(request, ModelState));
        }

        #endregion

        public bool CheckProperties(string PropertyName, int Id)
        {
            using (DB_Entities db = new DB_Entities())
            {
                int count = 0;

                if (Id != 0)
                    count = db.MstProperty.Where(p => p.PropertyName == PropertyName.Trim() && p.IsDeleted == false && p.PropertyId != Id).Count();
                else
                    count = db.MstProperty.Where(p => p.PropertyName == PropertyName.Trim() && p.IsDeleted == false).Count();

                return count > 0;
            }
        }

        public async Task<MstProperty> AddUpdatePropertyDB(MstProperty property)
        {
            string strAction = "Property updated";
            string strActivity = string.Format("Property titled '{0}' ", property.PropertyName);

            using (DB_Entities db = new DB_Entities())
            {
                if (property.PropertyId == 0)
                {
                    for (int i = 0; i < property.PropertyNames.Count; i++)
                    {
                        if (i == 0)
                        {
                            MstProperty newPropertyObj = new MstProperty()
                            {
                                PropertyName = property.PropertyNames.ElementAt(i).Name.Trim(),
                                IsActive = property.IsActive,
                                CreatedBy = new Guid(Session["UserID"].ToString()),
                                CreatedOn = DateTime.Now,
                                IsDeleted = false

                            };
                            db.MstProperty.Add(newPropertyObj);
                            await db.SaveChangesAsync();
                            property.PropertyId = newPropertyObj.PropertyId;
                        }

                        //Property Name
                        MstPropertyNames newMstPropertyName = new MstPropertyNames()
                        {

WebUI/3DLContentManagement/Views/ManageProperty/_AddUpdateProperty.cshtml
@model _3DLContentManagement.Models.PropertyViewModel

@using (Ajax.BeginForm("AddUpdateProperty", "ManageProperty", new { area = "" }, new AjaxOptions
{
    HttpMethod = "Post",
    OnSuccess = "LoadResultsAddProperty"
}, new { id = "frmManageProperty" }))
{
    @Html.HiddenFor(x => Model.PropertyId)
    @Html.HiddenFor(x => Model.IsActive)
    @Html.HiddenFor(x => Model.IsDeleted)
    <div class="row">
        <div class="form-group col-md-6 mb-0" style="margin-bottom: 3px;">
            <div class="col-xs-2" style="padding-left: 0px;">
                <span class="fa fa-plus" onclick="AddNameRow()" data-toggle='tooltip' data-placement='top' title='Add row for new language' style="font-size:24px;color:#a42639;cursor:pointer;"></span>
            </div>
            <div class="col-xs-10" style="padding-right: 0px;padding-left: 0px;">
                <label class="col-form-label" for="example-text-input">Property Name<span class="text-danger">*</span></label>
            </div>
        </div>
    </div>
    <div id="divName">
        @for (int i = 0; i < Model.PropertyNames.Count; i++)
        {
            <div class="row">
                @Html.HiddenFor(x => Model.PropertyNames[i].Id)
                @Html.HiddenFor(x => Model.PropertyNames[i].LanguageId)
                @Html.HiddenFor(x => Model.PropertyNames[i].IsDeleted)
                <div class="form-group col-md-6 mb-0">
                    <div class="col-xs-2" style="padding-left: 0px;">
                        <span class="fa fa-minus" data-id="PropertyNames[@i].IsDeleted" onclick="RemoveRow(this)" data-toggle='tooltip' data-placement='top' title='Remove' style="font-size:24px;color:#a42639;margin-top: 5px;cursor:pointer;"></span>
                    </div>
                    <div class="col-xs-10" style="padding-right: 0px;padding-left: 0px;">
                        @Html.TextBoxFor(x => Model.PropertyNames[i].Language, new { @class = "form-control language", @placeholder = "Select Language", @maxlength = "100" })
                        <div class="has-danger">
                            <div class="form-control-feedback">
                                @Html.ValidationMessageFor(x => Model.PropertyNames[i].Language)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 mb-0">
                    @Html.TextBoxFor(x => Model.PropertyNames[i].Name, new { @class = "form-control", @placeholder = "Property Name", @maxlength = "100" })
                    <div class="has-danger">
                        <div class="form-control-feedback">
                            @Html.ValidationMessageFor(x => Model.PropertyNames[i].Name)
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="row" style="position: absolute;margin-top: 55px;">
        <div class="col">
            <div class="input-group">
                <label>Status</label>
                <div id="radioPropertyBtn" class="btn-group" style="margin-left:10px;">
                    <a class="btn btn-success @(Model.IsActive == true ? "active" : "notActive")" data-toggle="tag" data-title="Active">Active</a>
                    <a class="btn btn-primary @(Model.IsActive == false ? "active" : "notActive")" data-toggle="tag" data-title="InActive">InActive</a>
                </div>
            </div>
        </div>
    </div>
    <div class="AddName" style="display:none">
        <div class="row">
            <input name="PropertyNames[{count}].ID" type="hidden" value="0">
            <input name="PropertyNames[{count}].LanguageId" type="hidden" id="PropertyNames_{count}__LanguageId" value="00000000-0000-0000-0000-000000000000">
            <input name="PropertyNames[{count}].IsDeleted" type="hidden" value="False">
            <div class="form-group col-md-6 mb-0">
                <div class="col-xs-2" style="padding-left: 0px;">
                    <span class="fa fa-minus" data-id="Names[{count}].IsDeleted" onclick="RemoveRow(this)" data-toggle='tooltip' data-placement='top' title='Remove' style="font-size:24px;color:#a42639;margin-top: 5px;cursor:pointer;"></span>
                </div>
                <div class="col-xs-10" style="padding-right: 0px;padding-left: 0px;">
                    <input class="form-control language" id="PropertyNames_{count}__Language" required data-val-required="Language is required." maxlength="100" name="PropertyNames[{count}].Language" placeholder="Select Language" type="text" value="">
                    <div class="has-danger">
                        <div class="form-control-feedback">
                            <span class="field-validation-valid" data-valmsg-for="PropertyNames[{count}].Language" data-valmsg-replace="false">
                                <span for="PropertyNames_{count}__Language" class="">Language is required.</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-6 mb-0">
                <input class="form-control" maxlength="100" name="PropertyNames[{count}].Name" required placeholder="Property Name" type="text" value="">
                <div class="has-danger">
                    <div class="form-control-feedback">
                        <span class="field-validation-valid" data-valmsg-for="PropertyNames[{count}].Name" data-valmsg-replace="false">
                            <span for="PropertyNames_{count}__Name" class="">Name is required.</span>
                        </span>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var availableLanguages = @Html.Raw(Json.Encode((IEnumerable<object>)ViewBag.Language));
    </script>
}